# Generated by Django 5.0.4 on 2024-05-02 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctor_time_slot',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='next_available_appointment_date',
        ),
    ]
